"""subiendo nuevas columnas

Revision ID: 348eac213cde
Revises: 61d30e9acf17
Create Date: 2023-03-30 17:56:26.266005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348eac213cde'
down_revision = '61d30e9acf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('oficina')

    # ### end Alembic commands ###
