"""subiendo las tablas de message, send, estado, usuario

Revision ID: 5185d02896f0
Revises: feb57a77d30a
Create Date: 2023-06-04 00:35:07.500387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5185d02896f0'
down_revision = 'feb57a77d30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('send',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estatus.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.create_unique_constraint(None, ['oficina'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('correo')
        batch_op.drop_column('oficina')

    op.drop_table('conversations')
    op.drop_table('send')
    op.drop_table('message')
    op.drop_table('estatus')
    # ### end Alembic commands ###
