"""subiendo columna de tabla estatus

Revision ID: 529290afddff
Revises: 5c3087aadc35
Create Date: 2023-06-04 02:05:21.052451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529290afddff'
down_revision = '5c3087aadc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatus', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
