"""agregando campos

Revision ID: 792f69c5b41b
Revises: 348eac213cde
Create Date: 2023-05-12 22:29:49.622025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792f69c5b41b'
down_revision = '348eac213cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ws_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['ws_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('state')
        batch_op.drop_column('ws_id')

    # ### end Alembic commands ###
