"""solucinando

Revision ID: 8ed556e00234
Revises: 6088c0f464c7
Create Date: 2023-05-29 12:22:53.465412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed556e00234'
down_revision = '6088c0f464c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
