"""subiendo

Revision ID: bb7f6fd2228e
Revises: 8ed556e00234
Create Date: 2023-05-30 09:45:16.361511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f6fd2228e'
down_revision = '8ed556e00234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sendmessage')
    op.drop_table('messagerecivided')
    op.drop_table('conversation')
    op.drop_table('estatus')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('state')

    op.create_table('estatus',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('estatus_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='estatus_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('estado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], name='conversation_agente_id_fkey'),
    sa.ForeignKeyConstraint(['estado_id'], ['estatus.id'], name='conversation_estado_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='conversation_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('messagerecivided',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='messagerecivided_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messagerecivided_pkey')
    )
    op.create_table('sendmessage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='sendmessage_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sendmessage_pkey')
    )
    # ### end Alembic commands ###
