"""status a agentes

Revision ID: f471c95783a8
Revises: bb7f6fd2228e
Create Date: 2023-05-30 10:36:13.295572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f471c95783a8'
down_revision = 'bb7f6fd2228e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
